import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import mongoose from "mongoose";
require("dotenv").config();

// db
async function connectDB() {
  await mongoose.connect(process.env.MONGO_URL);

  console.log("Connected to DB")

  // schemas
  const userSchema = new mongoose.Schema({
    name: String,
    email: String,
    password: String,
    avatar: String,
    bio: String,
    location: String,
    joined: String,
    todos: Array,
    account_status: String, // example: "admin"
    points: Number,
    total_sessions: Number,
    reported_distractions: Array,
  });

  // models
  const User = new mongoose.model("User", userSchema);
}

export default function Home() {
  return (
    <>
      <Head>
        <title>GaktooFocus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-3xl text-center">
        <h1 className="font-bold text-6xl">Welcome to GaktooFocus,</h1>
        <h2 className="mb-24">
          {" "}
          Where You Change Your Life By Power of Habits and Friends!
        </h2>
      </main>
    </>
  );
}
